package com.zyy.zyxk.common.constant;


public enum ErrorCode {
    SUCCESS(200, "操作成功"),
    PASSWORD_OR_ACCOUNT_ERROR(201, "密码或者账号错误！"),
    ACCOUNT_STOP_USING(202, "账号已停用，请联系管理员!"),
    ACCOUNT_UNUSUAL(203,"账户异常，请联系管理员！"),
    BAD_PARAM(204,"此功能出现异常，请联系管理员！"),
    TOKEN_EXPIRE(205,"用户身份过期,请重新登录!"),
    TOKEN_NOT_IN_REQUEST_HEADER(206,"认证信息缺失,请重新登录尝试"),
    TOKEN_EXCEPTION(207,"认证无效或过期，请重新登录尝试"),
    COPY_ERROR(300,"拷贝对象属性出错" ),
    USER_NOT_EXISTS(301,"用户不存在" ),
    ERROR_ACCOUNT(400,"用户名或密码错误"),
    NO_AUTH(401,"用户无权限访问此接口"),
    EMPTY_TOKEN(402,"无认证凭证"),
    NO_PASSWORD(403,"密码不能为空"),
    NO_USER_PHONE(405,"手机号不能为空"),
    NO_NEW_PASSWORD(406,"新密码不能为空"),
    NO_USER_ID(407,"用户id不能为空"),
    NO_USERNAME(408,"用户名不能为空"),
    No_Role_Name(409,"角色名称不能为空"),
    No_Role_Id(410,"角色id不能为空"),
    No_Authorities(411,"权限列表不能为空"),
    SERVER_ERROR(500, "服务器异常"),
    USER_ADD_ERROR(10000, "用户添加失败"),
    USER_DELETE_ERROR(10001, "用户删除失败"),
    USER_UPDATE_ERROR(10002, "用户更新失败"),
    USER_GET_ERROR(10003, "用户获取失败"),
    USER_GET_LIST_ERROR(10004, "用户列表获取失败"),
    USER_UPDATE_ERROR_NO_ACCOUNT(10005,"用户更新失败，无此用户"),
    USER_ROLE_ADD_ERROR(10006,"用户角色关系添加失败"),
    USER_ROLE_LIST_ERROR(10007,"用户角色关系列表获取失败"),
    USER_RESOURCE_LIST_ERROR(10008,"用户资源列表获取失败"),
    USER_EXISTED(10009,"帐号已存在"),
    USER_LOGIN_ERROR(10090,"用户登录失败"),
    USER_REGISTER_ERROR(10091,"用户注册失败"),
    USER_UPDATE_ERROR_NO_USER_ID(10005,"用户更新失败: 用户id不能为空"),
    RESOURCE_ADD_ERROR(10010, "资源添加失败"),
    RESOURCE_LIST_ERROR(10011,"资源列表获取失败"),
    ROLE_ADD_ERROR(10020, "角色添加失败"),
    ROLE_LIST_ERROR(10021,"角色列表获取失败"),
    ROLE_RESOURCE_ADD_ERROR(10022,"角色资源关系添加失败"),
    Role_Auth_List_Get_Error(10023,"角色权限关系列表获取失败"),
    Role_Name_Existed(10024,"该角色已存在"),
    Role_Id_Invalid(10025,"无效的角色id"),
    Role_Delete_Error(10026,"角色删除失败"),
    Role_Auth_List_Update_Error(10027,"角色权限关系列表更新失败"),
    ROLE_PLESE_ADD(10068,"请先创建角色"),
    ALIYUN_OSS_ERROR_BUCKET_EMPTY(10031,"bucket empty"),
    ALIYUN_OSS_ERROR_KEY_EMPTY(10032,"key empty"),
    ALIYUN_OSS_ERROR_FILE_EMPTY(10033,"file not exist"),
    ALIYUN_OSS_EXCEPTION_ERROR(10034,"OSSException"),
    ALIYUN_OSS_CLIENT_EXCEPTION_ERROR(10035,"ClientException"),
    UPLOAD_FILE_ERROR(10036,"上传失败"),
    UPLOAD_FILE_ERROR_NOT_EXIST(10037,"文件不存在"),
    UPLOAD_FILE_ERROR_NUMBER_OVERSTEP(10038,"上传文件数量超限"),
    COMPANY_ADD_ERROR(10041,"公司添加失败,信息不全"),
    COMPANY_DELETE_ERROR(10042,"公司删除失败"),
    COMPANY_UPDATE_ERROR(10043,"公司修改失败"),
    COMPANY_GET_ERROR(10044,"公司获取失败"),
    COMPANY_GET_LIST_ERROR(10045,"公司列表获取失败"),
    COMPANY_NAME_UNIQUE_ERROR(10046,"公司名称已被占用"),
    COMPANY_UPDATE_ERROR_NO_COMPANY(10047,"公司更新失败，无该公司信息"),
    COMPANY_PERMISSION_ERROR(10048,"没有权限查看或修改该公司下的信息"),
    COMPANY_USER_ERROR_NO_ASSOCIATION(10049,"没有关联公司信息"),
    COMPANY_USER_ERROR_NO_TARGET_COMPANY(10050,"操作失败，没有唯一目标公司"),
    WAREHOUSE_ADD_ERROR(10051,"仓库添加失败"),
    WAREHOUSE_DELETE_ERROR(10052,"仓库删除失败"),
    WAREHOUSE_UPDATE_ERROR(10053,"仓库修改失败"),
    WAREHOUSE_GET_ERROR(10054,"仓库获取失败"),
    WAREHOUSE_GET_LIST_ERROR(10055,"仓库列表获取失败"),
    WAREHOUSE_NUMBER_COMPANY_UNIQUE_ERROR(10056,"仓库编号冲突"),
    WAREHOUSE_NAME_COMPANY_UNIQUE_ERROR(100217,"仓库名称冲突"),
    WAREHOUSE_UPDATE_ERROR_NO_WAREHOUSE(10057,"仓库更新失败，无该仓库信息"),
    WAREHOUSE_UPDATE_ERROR_INVENTORY_NOT_NULL(10059,"操作失败，当前仓库有剩余库存"),
    CATEGORY_ADD_ERROR(10060,"品类添加失败,"),
    CATEGORY_ADD_ERROR_SAME_NAME(10061,"该品类名称已存在"),
    CATEGORY_DELETE_ERROR(10062,"品类删除失败"),
    CATEGORY_UPDATE_ERROR(10063,"品类修改失败"),
    CATEGORY_GET_ERROR(10064,"品类获取失败"),
    CATEGORY_ERROR_NO_CATEGORY(10065,"品类错误，没有该品类"),
    CATEGORY_UPDATE_ERROR_INVENTORY_NOT_NULL(10066,"操作失败，当前品类有物品存在"),
    CATEGORY_GET_LIST_ERROR(10067,"品类列表获取失败"),
    CREATE_PRODUCT_NUMBER_ERROR(10068,"物品编号创建失败失败"),
    PRODUCT_ADD_ERROR(10069,"物品添加失败"),
    PRODUCT_NAME_ERROR(10221,"物品名称已存在"),
    PRDOUCT_SKU_ERROR(10222,"物品SkuId已存在"),
    COMPANY_ADD_ERROR_CATEGORY_LEVEL(10070,"物品添加失败，品类不能选择一级分类"),
    PRODUCT_NULL_ERROR(10071,"请选择物品"),
    PRODUCT_UPDATE_ERROR(10072,"物品修改失败"),
    PRODUCT_DISABLE_ERROR_INVENTORY_NOT_NULL(10073,"操作失败，当前商品已被部分仓库选择"),
    PRODUCT_INVENTORY_NULL(10074,"该商品仓库库存为空"),
    USER_IS_DISABLED(10075,"该用户已被禁用"),
    NO_DELETE_AUTO(10076,"不可删除自己账号"),
    COMPANY_BE_DISABLED(10077,"公司已被禁用,请联系管理员启用"),
    COMPANY_DELETE(10078,"公司已被删除"),
    PRODUCT_ADD_ERROR_UNIQUE_NUMBER(10079,"物品编号重复"),
    ALREADY_EXIST_PHONE(10080,"手机号已存在"),
    OLD_PASSWORD_ERROR(10081,"旧密码错误,请重新输入"),
    PRODUCT_UNIT_TYPE_ERROR(10082,"物品计量单位缺失"),
    PRODUCT_GET_ERROR(10082,"物品获取失败"),
    PICTURE_ERROR_NOT_EXIST(10100,"图片信息不存在"),
    PICTURE_ERROR_SOURCE_NOT_CONSISTENCY(10101,"图片信息资源指向不一致"),
    PICTURE_ERROR_UNEQUAL_SIZE(10102,"上传图片数量出错"),
    OPERATION_ORDER_IN_ERROR_NULL(10200, "入库单为空"),
    OPERATION_ORDER_IN_ERROR_WAREHOUSE_NULL(10201, "未选择具体仓库"),
    OPERATION_ORDER_IN_ERROR_SKU_NULL(10202, "未选择具体商品"),
    OPERATION_ORDER_IN_ERROR_NO_SKU(10203, "未查询到对应商品"),
    INV_WHSEID(10223,"未查询到对应仓库"),
    INV_WHSE_DELETE(10224,"仓库已被删除请重新选择"),
    OPER_ORDER_ERROR(10256,"物品正在进行出入库或盘库请稍后操作"),
    OPERATION_ORDER_IN_ADD_ERROR(10204, "入库单创建失败"),
    OPERATION_ORDER_ADDD_TIME(10256,"出入库时间不能在未来嗷"),
    OPERATION_ORDER_IN_ADD_REPEAT_ERROR(10255,"入库单已存在请勿重复入库"),
    OPERATION_ORDER_IN_ADD_DETAIL_ERROR(10205, "入库单明细创建失败"),
    OPERATION_ORDER_IN_DETAIL_NULL_ERROR(10206, "入库单明细为空"),
    OPERATION_ORDER_IN_GET_LIST_NO_ERROR(10207, "未匹配到入库单"),
    OPERATION_ORDER_IN_ERROR_ID_NULL(10208, "入库单ID为空"),
    OPERATION_ORDER_IN_ERROR_DETAIL_ID_NULL(10217, "入库单明细ID为空"),
    OPERATION_ORDER_IN_ERROR_DETAIL_ID_ERROR(10209, "物品未匹配到对应库存信息"),
    OPERATION_ORDER_IN_ADJUST_DETAIL_AMOUNT_MINUS_ERROR(10210, "入库调整单明细数量为负数"),
    OPERATION_ORDER_IN_ADD_ADJUST_ORDER_ERROR(10211, "撤销失败，撤销后入库单包含的物品库存将为负数"),
    OPERATION_ORDER_IN_ADD_ADJUST_DETAIL_ERROR(10212, "入库调整单明细创建失败"),
    OPERATION_ORDER_IN_UPDATE_REVIEWED_TRUE_ERROR(10213, "入库单已核算，无法撤销"),
    OPERATION_ORDER_IN_UPDATE_DETAIL_ERROR(10214, "入库单明细修改失败"),
    OPERATION_ORDER_IN_UPDATE_ERROR(10216, "入库单修改失败"),
    OPERATION_ORDER_IN_GET_DETAIL_RECORD_ERROR(10218, "获取入库单物品修改记录失败"),
    OPERATION_ORDER_IN_GET_RECORD_TIME_NULL(10219, "获取入库单统计列表时间为空"),
    OPERATION_ORDER_IN_ADJUST_AMOUNT_GREATER_STORAGE_ERROR(10220, "入库单调整出库量超出当前库存数量"),
    OPERATION_ORDER_OUT_ERROR_NULL(10300, "出库单为空"),
    OPERATION_ORDER_OUT_ERROR_WAREHOUSE_NULL(10301, "未选择具体仓库"),
    OPERATION_ORDER_OUT_ERROR_SKU_NULL(10302, "未选择具体商品"),
    OPERATION_ORDER_OUT_ERROR_NO_SKU(10303, "未查询到对应商品"),
    OPERATION_ORDER_OUT_ADD_ERROR(10304, "出库单创建失败"),
    OPERATION_ORDER_OUT_PRODUCT_STORAGE(10555,"出库失败，物品出库数量不可大于库存数量"),
    OPERATION_ORDER_OUT_ADD_DETAIL_ERROR(10305, "出库单明细创建失败"),
    OPERATION_ORDER_OUT_DETAIL_NULL_ERROR(10306, "出库单明细为空"),
    OPERATION_ORDER_OUT_GET_LIST_NO_ERROR(10307, "未匹配到出库单"),
    OPERATION_ORDER_OUT_ERROR_ID_NULL(10308, "出库单ID为空"),
    OPERATION_ORDER_OUT_ERROR_DETAIL_ID_NULL(10317, "出库单明细ID为空"),
    OPERATION_ORDER_OUT_ERROR_DETAIL_ID_ERROR(10309, "出库单明细id未匹配到对应明细"),
    OPERATION_ORDER_OUT_ADJUST_DETAIL_AMOUNT_MINUS_ERROR(10310, "出库调整单明细数量为负数"),
    OPERATION_ORDER_OUT_ADD_ADJUST_ORDER_ERROR(10311, "出库调整单创建失败"),
    OPERATION_ORDER_OUT_ADD_ADJUST_DETAIL_ERROR(10312, "出库调整单明细创建失败"),
    OPERATION_ORDER_OUT_UPDATE_REVIEWED_TRUE_ERROR(10313, "出库单已核算，无法修改"),
    OPERATION_ORDER_OUT_UPDATE_DETAIL_ERROR(10314, "出库单明细修改失败"),
    OPERATION_ORDER_OUT_UPDATE_ERROR(10316, "出库单修改失败"),
    OPERATION_ORDER_OUT_GET_DETAIL_RECORD_ERROR(10318, "获取出库单物品修改记录失败"),
    OPERATION_ORDER_OUT_GET_RECORD_TIME_NULL(10319, "获取出库单统计列表时间为空"),
    OPERATION_ORDER_OUT_ADJUST_AMOUNT_GREATER_STORAGE_ERROR(10320, "出库单调整出库量超出当前库存数量"),
    AMOUNT_MAX_ERROR(10257,"最大操作数量不可超过八位"),

    HAVE_PRODUCT_ASSOCIATION(10215,"当前类有物品关联，无法删除"),
    COMPANY_ERROR_STAND(10216,"不可禁用自己所在公司"),
    ROLE_COMMENT_ERROR(10217,"角色描述过长"),
    RSC_PRODUCT_STORAGE_NO_NULL(10400, "未查询到对应库存信息"),
    RSC_PRODUCT_STORAGE_UPDATE_ERROR(10401, "库存信息修改失败"),
    PRODUCT_IS_EXIST(10402,"该商品已存在"),
    REVIEW_ORDER_ERROR_UNCOMPLETE_REPEAT(10500, "当前存在未完成盘库单"),
    REVIEW_ORDER_ADD_ERROR(10501, "盘库创建失败"),
    REVIEW_ORDER_DETAIL_ERROR(10502,"暂无对应的盘库单明细"),
    REVIEW_ORDER_NULL(10503,"暂无盘库单信息"),
    BIND_ERROR(99900, "参数校验失败"),
    CONSTRAINT_ERROR(99910, "全局异常"),
    JWT_ERROR(99920,"认证失败,请重新登录后尝试"),
    COMMON_ERROR(99999, "操作失败"),
    EXCL_NULL_ERROR(99930,"EXCL为空"),
    EXCL_TYPE_ERROR(99940,"文件格式错误"),
    SIGN_TIME_ERROR(99950,"签名已过期"),
    SIGN_ERROR(99960,"签名有误"),
    PAYMENT_AMOUNT_NULL_ERROR(99970,"付款金额不能为空"),
    PAYMENT_TIME_ERROR(99971,"付款时间不能在未来"),
    SUPPLIER_NULL_ERROR(99972,"未匹配到供应商"),
    SUPPLIER_NOTNULL_ERROR(99973,"供应商已存在请确认状态");



    private int code;
    private String message;

    private ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }

    public static ErrorCode getEnum(int code){
        for(ErrorCode item: ErrorCode.values()){
            if(code == item.getCode()){
                return item;
            }
        }

        return ErrorCode.COMMON_ERROR;
    }
}
